<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.CloudStorage" />
    <PackageReference Include="LagoVista.IoT.Billing.Managers" />
    <PackageReference Include="LagoVista.IoT.DeviceAdmin" />
    <PackageReference Include="LagoVista.IoT.DeviceManagement.Core" />
    <PackageReference Include="LagoVista.IoT.DeviceMessaging.Admin" />
    <PackageReference Include="LagoVista.IoT.Verifiers" />
    <PackageReference Include="LagoVista.Manufacturing" />
    <PackageReference Include="LagoVista.IoT.Runtime.Core" />
    <PackageReference Include="LagoVista.IoT.Pipeline.Admin" />
    <PackageReference Include="LagoVista.IoT.Deployment.Admin" />
    <PackageReference Include="LagoVista.IoT.Simulator.Admin" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <None Update="T4ResourceGenerator.tt">
      <LastGenOutput>T4ResourceGenerator.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\StarterKitResources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="T4ResourceGenerator.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>T4ResourceGenerator.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
